server:
  port: 8080
  servlet:
    context-path: /webmvc
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
#spring:
#  security:
#    user:
#      name: user
#      password: password
#      roles: ROLE1,ROLE2   